"""
Generate Commerce faculty programme JSON files from handbook data.
Run once to create all programme files under faculties/commerce/majors/
"""
import json
import os

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "handbook", "faculties", "commerce", "majors")
os.makedirs(OUTPUT_DIR, exist_ok=True)

programmes = [
    # ============================================================
    # BACHELOR OF BUSINESS SCIENCE (BBusSci) - 4 year, NQF 8
    # ============================================================
    {
        "programme_code": "CB003BUS01",
        "programme_name": "Bachelor of Business Science in Actuarial Science",
        "degree": "BBusSci",
        "specialisation": "Actuarial Science",
        "nqf_level": 8,
        "minimum_credits": 528,
        "duration_years": 4,
        "slug": "bbusc-actuarial-science",
        "department": "management-studies",
        "years": [
            {"year": 1, "credits": 180, "courses": [
                {"code": "ACC1006F", "title": "Financial Accounting", "credits": 18, "nqf": 5},
                {"code": "BUS1036F", "title": "Evidence-based Management", "credits": 18, "nqf": 5},
                {"code": "CSC1015F", "title": "Computer Science 1015", "credits": 18, "nqf": 5, "or": "INF1002F"},
                {"code": "INF1002F", "title": "Foundations of Information Systems", "credits": 18, "nqf": 5, "or": "CSC1015F"},
                {"code": "ECO1010F", "title": "Microeconomics I", "credits": 18, "nqf": 5},
                {"code": "MAM1031F", "title": "Mathematics 1031", "credits": 18, "nqf": 5},
                {"code": "MAM1032S", "title": "Mathematics 1032", "credits": 18, "nqf": 5},
                {"code": "BUS1003H", "title": "Introduction to Actuarial Science", "credits": 18, "nqf": 5},
                {"code": "ACC1011S", "title": "Financial Reporting I", "credits": 18, "nqf": 5},
                {"code": "ECO1011S", "title": "Macroeconomics I", "credits": 18, "nqf": 5},
                {"code": "STA1006S", "title": "Mathematical Statistics I", "credits": 18, "nqf": 5},
            ]},
            {"year": 2, "credits": 186, "courses": [
                {"code": "CML1001F", "title": "Business Law I", "credits": 18, "nqf": 5},
                {"code": "ECO2003F", "title": "Microeconomics II", "credits": 18, "nqf": 6},
                {"code": "STA2004F", "title": "Statistical Theory & Inference", "credits": 24, "nqf": 6},
                {"code": "MAM2010F", "title": "Advanced Calculus (2AC)", "credits": 12, "nqf": 6},
                {"code": "MAM2011F", "title": "Linear Algebra (2LA)", "credits": 12, "nqf": 6},
                {"code": "MAM2012S", "title": "Differential Equations (2DE)", "credits": 12, "nqf": 6},
                {"code": "MAM2014S", "title": "Real Analysis (2RA)", "credits": 12, "nqf": 6},
                {"code": "BUS2016H", "title": "Actuarial Science I: Financial Mathematics", "credits": 18, "nqf": 6},
                {"code": "ECO2004S", "title": "Macroeconomics II", "credits": 18, "nqf": 6},
                {"code": "FTX2024F", "title": "Financial Management", "credits": 18, "nqf": 6, "or": "FTX2024S"},
                {"code": "STA2005S", "title": "Linear Models", "credits": 24, "nqf": 6},
            ]},
            {"year": 3, "credits": 180, "courses": [
                {"code": "BUS3018F", "title": "Actuarial Science II: Models", "credits": 18, "nqf": 7},
                {"code": "BUS3039F", "title": "People Management", "credits": 18, "nqf": 7, "or": "BUS3039S"},
                {"code": "STA3041F", "title": "Stochastic Processes & Time Series", "credits": 36, "nqf": 7},
                {"code": "STA3045F", "title": "Stochastic Processes and Distribution", "credits": 36, "nqf": 7},
                {"code": "BUS3024S", "title": "Actuarial Science II: Contingencies", "credits": 18, "nqf": 7},
                {"code": "PHI2043S", "title": "Business Ethics", "credits": 18, "nqf": 6},
                {"code": "STA3047S", "title": "Introduction to Machine Learning", "credits": 6, "nqf": 7},
                {"code": "STA3048S", "title": "Statistical Modelling and Bayesian Analysis", "credits": 30, "nqf": 7},
            ]},
            {"year": 4, "credits": 156, "courses": [
                {"code": "BUS4028F", "title": "Actuarial Science III: Financial Economics", "credits": 21, "nqf": 7},
                {"code": "BUS4027W", "title": "Actuarial Science III: Assets", "credits": 54, "nqf": 8},
                {"code": "BUS4050H", "title": "Strategic Thinking", "credits": 18, "nqf": 8},
                {"code": "BUS4029H", "title": "Actuarial Research Project", "credits": 36, "nqf": 8},
                {"code": "BUS4034S", "title": "Professional Communication (Actuarial Science)", "credits": 27, "nqf": 8},
            ]},
        ]
    },
    {
        "programme_code": "CB003BUS09",
        "programme_name": "Bachelor of Business Science in Actuarial Science specialising in Quantitative Finance",
        "degree": "BBusSci",
        "specialisation": "Actuarial Science - Quantitative Finance",
        "nqf_level": 8,
        "minimum_credits": 528,
        "duration_years": 4,
        "slug": "bbusc-actuarial-quantitative-finance",
        "department": "management-studies",
        "years": [
            {"year": 1, "credits": 180, "courses": [
                {"code": "ACC1006F", "title": "Financial Accounting", "credits": 18, "nqf": 5},
                {"code": "BUS1036F", "title": "Evidence-based Management", "credits": 18, "nqf": 5},
                {"code": "CSC1015F", "title": "Computer Science 1015", "credits": 18, "nqf": 5, "or": "INF1002F"},
                {"code": "INF1002F", "title": "Foundations of Information Systems", "credits": 18, "nqf": 5, "or": "CSC1015F"},
                {"code": "ECO1010F", "title": "Microeconomics I", "credits": 18, "nqf": 5},
                {"code": "MAM1031F", "title": "Mathematics 1031", "credits": 18, "nqf": 5},
                {"code": "MAM1032S", "title": "Mathematics 1032", "credits": 18, "nqf": 5},
                {"code": "BUS1003H", "title": "Introduction to Actuarial Science", "credits": 18, "nqf": 5},
                {"code": "ACC1011S", "title": "Financial Reporting I", "credits": 18, "nqf": 5},
                {"code": "ECO1011S", "title": "Macroeconomics I", "credits": 18, "nqf": 5},
                {"code": "STA1006S", "title": "Mathematical Statistics I", "credits": 18, "nqf": 5},
            ]},
            {"year": 2, "credits": 186, "courses": [
                {"code": "CML1001F", "title": "Business Law I", "credits": 18, "nqf": 5},
                {"code": "ECO2003F", "title": "Microeconomics II", "credits": 18, "nqf": 6},
                {"code": "STA2004F", "title": "Statistical Theory & Inference", "credits": 24, "nqf": 6},
                {"code": "MAM2010F", "title": "Advanced Calculus (2AC)", "credits": 12, "nqf": 6},
                {"code": "MAM2011F", "title": "Linear Algebra (2LA)", "credits": 12, "nqf": 6},
                {"code": "MAM2012S", "title": "Differential Equations (2DE)", "credits": 12, "nqf": 6},
                {"code": "MAM2014S", "title": "Real Analysis (2RA)", "credits": 12, "nqf": 6},
                {"code": "BUS2016H", "title": "Financial Mathematics", "credits": 18, "nqf": 6},
                {"code": "ECO2004S", "title": "Macroeconomics II", "credits": 18, "nqf": 6},
                {"code": "FTX2024S", "title": "Financial Management", "credits": 18, "nqf": 6},
                {"code": "STA2005S", "title": "Linear Models", "credits": 24, "nqf": 6},
            ]},
            {"year": 3, "credits": 198, "courses": [
                {"code": "BUS2033F", "title": "Professional Communication", "credits": 18, "nqf": 6, "or": "BUS2033S"},
                {"code": "BUS3039F", "title": "People Management", "credits": 18, "nqf": 7, "or": "BUS3039S"},
                {"code": "FTX3044F", "title": "Investment Management A", "credits": 18, "nqf": 7},
                {"code": "STA3041F", "title": "Stochastic Processes & Time Series", "credits": 36, "nqf": 7},
                {"code": "STA3045F", "title": "Stochastic Processes and Distribution", "credits": 36, "nqf": 7},
                {"code": "FTX3045S", "title": "Investment Management B", "credits": 18, "nqf": 7},
                {"code": "PHI2043S", "title": "Business Ethics", "credits": 18, "nqf": 6},
                {"code": "STA3047S", "title": "Introduction to Machine Learning", "credits": 6, "nqf": 7},
                {"code": "STA3048S", "title": "Statistical Modelling and Bayesian Analysis", "credits": 30, "nqf": 7},
            ]},
            {"year": 4, "credits": 129, "courses": [
                {"code": "BUS4028F", "title": "Actuarial Science III: Financial Economics", "credits": 21, "nqf": 7},
                {"code": "FTX4086F", "title": "Alternative Investments", "credits": 18, "nqf": 8},
                {"code": "BUS4050H", "title": "Strategic Thinking", "credits": 18, "nqf": 8},
                {"code": "BUS4053H", "title": "Quantitative Finance Project", "credits": 36, "nqf": 8},
                {"code": "BUS4087S", "title": "Quantitative Finance Selected Topics", "credits": 18, "nqf": 8},
                {"code": "FTX4056S", "title": "Applied Investments", "credits": 18, "nqf": 8},
            ]},
        ]
    },
    {
        "programme_code": "CB004STA13",
        "programme_name": "Bachelor of Business Science specialising in Statistics and Data Science",
        "degree": "BBusSci",
        "specialisation": "Statistics and Data Science",
        "nqf_level": 8,
        "minimum_credits": 528,
        "duration_years": 4,
        "slug": "bbusc-statistics-data-science",
        "department": "statistical-sciences",
        "years": [
            {"year": 1, "credits": 168, "courses": [
                {"code": "ACC1021F", "title": "Accounting for Business I", "credits": 15, "nqf": 5},
                {"code": "ACC1022Z", "title": "Accounting for Business II", "credits": 9, "nqf": 5},
                {"code": "BUS1036F", "title": "Evidence-based Management", "credits": 18, "nqf": 5},
                {"code": "ECO1010F", "title": "Microeconomics I", "credits": 18, "nqf": 5},
                {"code": "CSC1015F", "title": "Computer Science 1015", "credits": 18, "nqf": 5},
                {"code": "MAM1031F", "title": "Mathematics 1031", "credits": 18, "nqf": 5},
                {"code": "MAM1032S", "title": "Mathematics 1032", "credits": 18, "nqf": 5},
                {"code": "CSC1016S", "title": "Computer Science 1016", "credits": 18, "nqf": 5},
                {"code": "ECO1011S", "title": "Macroeconomics I", "credits": 18, "nqf": 5},
                {"code": "STA1000S", "title": "Introductory Statistics", "credits": 18, "nqf": 5, "or": "STA1006S"},
            ]},
            {"year": 2, "credits": 186, "courses": [
                {"code": "ECO2003F", "title": "Microeconomics II", "credits": 18, "nqf": 6},
                {"code": "MAM2010F", "title": "Advanced Calculus (2AC)", "credits": 12, "nqf": 6},
                {"code": "MAM2011F", "title": "Linear Algebra (2LA)", "credits": 12, "nqf": 6},
                {"code": "MAM2012S", "title": "Differential Equations (2DE)", "credits": 12, "nqf": 6},
                {"code": "MAM2014S", "title": "Real Analysis (2RA)", "credits": 12, "nqf": 6},
                {"code": "PHI2043S", "title": "Business Ethics", "credits": 18, "nqf": 6},
                {"code": "BUS2010F", "title": "Marketing I", "credits": 18, "nqf": 6},
                {"code": "CML1001F", "title": "Business Law I", "credits": 18, "nqf": 5, "or": "CML1001S"},
                {"code": "ECO2004S", "title": "Macroeconomics II", "credits": 18, "nqf": 6},
                {"code": "STA2004F", "title": "Statistical Theory & Inference", "credits": 24, "nqf": 6},
                {"code": "STA2005S", "title": "Linear Models", "credits": 24, "nqf": 6},
            ]},
            {"year": 3, "credits": 198, "note": "Includes Mathematical Statistics OR Applied Statistics stream option", "courses": [
                {"code": "FTX2020F", "title": "Business Finance", "credits": 18, "nqf": 6, "or": "FTX2024F"},
                {"code": "BUS3039F", "title": "People Management", "credits": 18, "nqf": 7, "or": "BUS3039S"},
                {"code": "CSC2001F", "title": "Computer Science 2001", "credits": 24, "nqf": 6},
                {"code": "CSC2002S", "title": "Computer Science 2002", "credits": 24, "nqf": 6},
                {"code": "ECO3021S", "title": "Quantitative Methods in Economics", "credits": 18, "nqf": 7},
                {"code": "INF2006F", "title": "Business Intelligence & Analytics", "credits": 6, "nqf": 6},
                {"code": "INF2007F", "title": "Applying Database Principles", "credits": 12, "nqf": 6},
                {"code": "STA3022F", "title": "Applied Multivariate Data Analysis", "credits": 36, "nqf": 7},
                {"code": "STA3045F", "title": "Stochastic Processes and Distribution", "credits": 36, "nqf": 7},
            ]},
            {"year": 4, "credits": 160, "courses": [
                {"code": "STA4010W", "title": "Topics in Statistics & Operational Research", "credits": 142, "nqf": 8},
                {"code": "BUS4050H", "title": "Strategic Thinking", "credits": 18, "nqf": 8},
            ]},
        ]
    },
    {
        "programme_code": "CB004FTX05",
        "programme_name": "Bachelor of Business Science specialising in Finance",
        "degree": "BBusSci",
        "specialisation": "Finance",
        "nqf_level": 8,
        "minimum_credits": 528,
        "duration_years": 4,
        "slug": "bbusc-finance",
        "department": "finance-and-tax",
        "years": [
            {"year": 1, "credits": 150, "courses": [
                {"code": "ACC1021F", "title": "Accounting for Business I", "credits": 15, "nqf": 5},
                {"code": "ACC1022Z", "title": "Accounting for Business II", "credits": 9, "nqf": 5},
                {"code": "ECO1010F", "title": "Microeconomics I", "credits": 18, "nqf": 5},
                {"code": "INF1002F", "title": "Foundations of Information Systems", "credits": 18, "nqf": 5},
                {"code": "MAM1010F", "title": "Mathematics 1010", "credits": 18, "nqf": 5},
                {"code": "BUS1036S", "title": "Evidence-based Management", "credits": 18, "nqf": 5},
                {"code": "ECO1011S", "title": "Macroeconomics I", "credits": 18, "nqf": 5},
                {"code": "MAM1012S", "title": "Mathematics 1012", "credits": 18, "nqf": 5},
                {"code": "STA1000S", "title": "Introductory Statistics", "credits": 18, "nqf": 5},
            ]},
            {"year": 2, "credits": 168, "courses": [
                {"code": "BUS2010F", "title": "Marketing I", "credits": 18, "nqf": 6},
                {"code": "CML1001F", "title": "Business Law I", "credits": 18, "nqf": 5},
                {"code": "ECO2003F", "title": "Microeconomics II", "credits": 18, "nqf": 6},
                {"code": "STA2020F", "title": "Applied Statistics", "credits": 24, "nqf": 6},
                {"code": "ACC2022H", "title": "Management Accounting I", "credits": 18, "nqf": 6},
                {"code": "ECO2007S", "title": "Co-operation and Competition", "credits": 18, "nqf": 6},
                {"code": "ECO2004S", "title": "Macroeconomics II", "credits": 18, "nqf": 6},
                {"code": "FTX2024F", "title": "Financial Management", "credits": 18, "nqf": 6, "or": "FTX2024S"},
                {"code": "PHI2043S", "title": "Business Ethics", "credits": 18, "nqf": 6},
            ]},
            {"year": 3, "credits": 162, "courses": [
                {"code": "ECO3020F", "title": "Advanced Macro & Microeconomics", "credits": 18, "nqf": 7},
                {"code": "FTX3044F", "title": "Investment Management A", "credits": 18, "nqf": 7},
                {"code": "STA3022F", "title": "Applied Multivariate Data Analysis", "credits": 36, "nqf": 7},
                {"code": "BUS2033F", "title": "Professional Communication", "credits": 18, "nqf": 6, "or": "BUS2033S"},
                {"code": "BUS3039F", "title": "People Management", "credits": 18, "nqf": 7, "or": "BUS3039S"},
                {"code": "ECO3021S", "title": "Quantitative Methods in Economics", "credits": 18, "nqf": 7},
                {"code": "FTX3045S", "title": "Investment Management B", "credits": 18, "nqf": 7},
            ]},
            {"year": 4, "credits": 126, "courses": [
                {"code": "FTX4057F", "title": "Applied Corporate Finance", "credits": 18, "nqf": 8},
                {"code": "FTX4086F", "title": "Alternative Investments", "credits": 18, "nqf": 8},
                {"code": "BUS4050H", "title": "Strategic Thinking", "credits": 18, "nqf": 8},
                {"code": "FTX4051H", "title": "Finance Research Project", "credits": 36, "nqf": 8},
                {"code": "FTX4056S", "title": "Applied Investments", "credits": 18, "nqf": 8},
                {"code": "FTX4087S", "title": "Topics in Banking and Treasury Management", "credits": 18, "nqf": 8},
            ]},
        ]
    },
    {
        "programme_code": "CB004FTX04",
        "programme_name": "Bachelor of Business Science specialising in Finance with Accounting",
        "degree": "BBusSci",
        "specialisation": "Finance with Accounting",
        "nqf_level": 8,
        "minimum_credits": 528,
        "duration_years": 4,
        "slug": "bbusc-finance-accounting",
        "department": "finance-and-tax",
        "years": [
            {"year": 1, "credits": 159, "courses": [
                {"code": "ACC1006F", "title": "Financial Accounting", "credits": 18, "nqf": 5},
                {"code": "ECO1010F", "title": "Microeconomics I", "credits": 18, "nqf": 5},
                {"code": "INF1002F", "title": "Foundations of Information Systems", "credits": 18, "nqf": 5},
                {"code": "MAM1010F", "title": "Mathematics 1010", "credits": 18, "nqf": 5},
                {"code": "ACC1011S", "title": "Financial Reporting I", "credits": 18, "nqf": 5},
                {"code": "ACC1015S", "title": "Business Acumen for Accountants", "credits": 15, "nqf": 5},
                {"code": "ECO1011S", "title": "Macroeconomics I", "credits": 18, "nqf": 5},
                {"code": "MAM1012S", "title": "Mathematics 1012", "credits": 18, "nqf": 5},
                {"code": "STA1000S", "title": "Introductory Statistics", "credits": 18, "nqf": 5},
            ]},
            {"year": 2, "credits": 180, "courses": [
                {"code": "ACC2023H", "title": "Taxation I", "credits": 18, "nqf": 6},
                {"code": "BUS2010F", "title": "Marketing I", "credits": 18, "nqf": 6},
                {"code": "CML1001F", "title": "Business Law I", "credits": 18, "nqf": 5},
                {"code": "ECO2003F", "title": "Microeconomics II", "credits": 18, "nqf": 6},
                {"code": "STA2020F", "title": "Applied Statistics", "credits": 24, "nqf": 6},
                {"code": "ACC2022H", "title": "Management Accounting I", "credits": 18, "nqf": 6},
                {"code": "CML2010Z", "title": "Business Law II", "credits": 12, "nqf": 6},
                {"code": "ECO2004S", "title": "Macroeconomics II", "credits": 18, "nqf": 6},
                {"code": "FTX2024F", "title": "Financial Management", "credits": 18, "nqf": 6, "or": "FTX2024S"},
                {"code": "PHI2043S", "title": "Business Ethics", "credits": 18, "nqf": 6},
            ]},
            {"year": 3, "credits": 170, "courses": [
                {"code": "CML2001F", "title": "Company Law", "credits": 18, "nqf": 6},
                {"code": "FTX3044F", "title": "Investment Management A", "credits": 18, "nqf": 7},
                {"code": "INF2004F", "title": "Information Technology in Business", "credits": 18, "nqf": 6},
                {"code": "ACC2012W", "title": "Financial Reporting II", "credits": 36, "nqf": 6},
                {"code": "ACC2018H", "title": "Governance, Audit and Assurance I", "credits": 18, "nqf": 6},
                {"code": "ACC3023W", "title": "Management Accounting II", "credits": 26, "nqf": 7},
                {"code": "BUS3039F", "title": "People Management", "credits": 18, "nqf": 7, "or": "BUS3039S"},
                {"code": "FTX3045S", "title": "Investment Management B", "credits": 18, "nqf": 7},
            ]},
            {"year": 4, "credits": 166, "courses": [
                {"code": "FTX4057F", "title": "Applied Corporate Finance", "credits": 18, "nqf": 8},
                {"code": "ACC3009W", "title": "Financial Reporting III", "credits": 36, "nqf": 7},
                {"code": "BUS4050H", "title": "Strategic Thinking", "credits": 18, "nqf": 8},
                {"code": "ACC3004W", "title": "Taxation II", "credits": 32, "nqf": 7},
                {"code": "ACC3022W", "title": "Governance, Audit and Assurance II", "credits": 26, "nqf": 7},
                {"code": "FTX4087S", "title": "Topics in Banking and Treasury Management", "credits": 18, "nqf": 8},
                {"code": "FTX4056S", "title": "Applied Investments", "credits": 18, "nqf": 8},
            ]},
        ]
    },
    {
        "programme_code": "CB004CSC05",
        "programme_name": "Bachelor of Business Science specialising in Computer Science",
        "degree": "BBusSci",
        "specialisation": "Computer Science",
        "nqf_level": 8,
        "minimum_credits": 528,
        "duration_years": 4,
        "slug": "bbusc-computer-science",
        "department": "computer-science",
        "years": [
            {"year": 1, "credits": 162, "courses": [
                {"code": "BUS1036F", "title": "Evidence-based Management", "credits": 18, "nqf": 5},
                {"code": "CSC1015F", "title": "Computer Science 1015", "credits": 18, "nqf": 5},
                {"code": "ECO1010F", "title": "Microeconomics I", "credits": 18, "nqf": 5},
                {"code": "MAM1031F", "title": "Mathematics 1031", "credits": 18, "nqf": 5, "or": "MAM1004F"},
                {"code": "MAM1008S", "title": "Introduction to Discrete Mathematics", "credits": 18, "nqf": 5},
                {"code": "CSC1016S", "title": "Computer Science 1016", "credits": 18, "nqf": 5},
                {"code": "ECO1011S", "title": "Macroeconomics I", "credits": 18, "nqf": 5},
                {"code": "STA1000S", "title": "Introductory Statistics", "credits": 18, "nqf": 5},
            ]},
            {"year": 2, "credits": 168, "courses": [
                {"code": "ACC1021F", "title": "Accounting for Business I", "credits": 15, "nqf": 5},
                {"code": "ACC1022Z", "title": "Accounting for Business II", "credits": 9, "nqf": 5},
                {"code": "CSC2001F", "title": "Computer Science 2001", "credits": 24, "nqf": 6},
                {"code": "CML1001F", "title": "Business Law I", "credits": 18, "nqf": 5},
                {"code": "INF2009F", "title": "Systems Analysis", "credits": 18, "nqf": 6},
                {"code": "CSC2002S", "title": "Computer Science 2002", "credits": 24, "nqf": 6},
                {"code": "CSC2004Z", "title": "Programming Assessment", "credits": 0, "nqf": 6},
                {"code": "INF2011S", "title": "Systems Design & Development", "credits": 18, "nqf": 7},
                {"code": "PHI2043S", "title": "Business Ethics", "credits": 18, "nqf": 6},
            ]},
            {"year": 3, "credits": 144, "courses": [
                {"code": "BUS3039F", "title": "People Management", "credits": 18, "nqf": 7, "or": "BUS3039S"},
                {"code": "CSC3002F", "title": "Computer Science 3002", "credits": 36, "nqf": 7},
                {"code": "BUS3038S", "title": "Introduction to Project Management", "credits": 18, "nqf": 7},
                {"code": "BUS2010S", "title": "Marketing I", "credits": 18, "nqf": 6},
                {"code": "CSC3003S", "title": "Computer Science 3003", "credits": 36, "nqf": 7},
                {"code": "FTX2020F", "title": "Business Finance", "credits": 18, "nqf": 6},
            ]},
            {"year": 4, "credits": 160, "courses": [
                {"code": "BUS4050H", "title": "Strategic Thinking", "credits": 18, "nqf": 8},
                {"code": "CSC4019Z", "title": "Research and Innovation", "credits": 16, "nqf": 8},
                {"code": "CSC4020Z", "title": "Functional Programming", "credits": 12, "nqf": 8},
                {"code": "CSC4021Z", "title": "Compilers I", "credits": 12, "nqf": 8},
                {"code": "CSC4002W", "title": "Computer Science Honours Project", "credits": 60, "nqf": 8},
            ]},
        ]
    },
    {
        "programme_code": "CB004INF01",
        "programme_name": "Bachelor of Business Science specialising in Information Systems",
        "degree": "BBusSci",
        "specialisation": "Information Systems",
        "nqf_level": 8,
        "minimum_credits": 528,
        "duration_years": 4,
        "slug": "bbusc-information-systems",
        "department": "information-systems",
        "years": [
            {"year": 1, "credits": 150, "courses": [
                {"code": "ACC1021F", "title": "Accounting for Business I", "credits": 15, "nqf": 5},
                {"code": "ACC1022Z", "title": "Accounting for Business II", "credits": 9, "nqf": 5},
                {"code": "BUS1036F", "title": "Evidence-based Management", "credits": 18, "nqf": 5},
                {"code": "INF1002F", "title": "Foundations of Information Systems", "credits": 18, "nqf": 5, "or": "CSC1015F"},
                {"code": "ECO1010F", "title": "Microeconomics I", "credits": 18, "nqf": 5},
                {"code": "MAM1010F", "title": "Mathematics 1010", "credits": 18, "nqf": 5},
                {"code": "ECO1011S", "title": "Macroeconomics I", "credits": 18, "nqf": 5},
                {"code": "MAM1012S", "title": "Mathematics 1012", "credits": 18, "nqf": 5},
                {"code": "STA1000S", "title": "Introductory Statistics", "credits": 18, "nqf": 5},
            ]},
            {"year": 2, "credits": 150, "courses": [
                {"code": "INF2003F", "title": "Commercial Programming", "credits": 18, "nqf": 6},
                {"code": "INF2006F", "title": "Business Intelligence and Analytics", "credits": 6, "nqf": 6},
                {"code": "INF2007F", "title": "Applying Database Principles", "credits": 12, "nqf": 6},
                {"code": "INF2009F", "title": "Systems Analysis", "credits": 18, "nqf": 6},
                {"code": "FTX2020F", "title": "Business Finance", "credits": 18, "nqf": 6},
                {"code": "STA2020S", "title": "Business Statistics", "credits": 24, "nqf": 6},
                {"code": "INF2010S", "title": "IT Architecture", "credits": 18, "nqf": 7},
                {"code": "INF2011S", "title": "Systems Design & Development", "credits": 18, "nqf": 7},
                {"code": "CML1001F", "title": "Business Law I", "credits": 18, "nqf": 5, "or": "CML1001S"},
            ]},
            {"year": 3, "credits": 156, "courses": [
                {"code": "BUS2010F", "title": "Marketing I", "credits": 18, "nqf": 6},
                {"code": "BUS3039F", "title": "People Management", "credits": 18, "nqf": 7, "or": "BUS3039S"},
                {"code": "INF3014F", "title": "Electronic Commerce", "credits": 18, "nqf": 7},
                {"code": "INF3003W", "title": "Systems Development Project I", "credits": 48, "nqf": 7},
                {"code": "BUS2033S", "title": "Professional Communication", "credits": 18, "nqf": 6},
                {"code": "INF3012S", "title": "BPM & Enterprise Systems", "credits": 18, "nqf": 7},
                {"code": "PHI2043S", "title": "Business Ethics", "credits": 18, "nqf": 6},
            ]},
            {"year": 4, "credits": 158, "courses": [
                {"code": "INF4026F", "title": "Application and Technical Development", "credits": 20, "nqf": 8},
                {"code": "BUS4050H", "title": "Strategic Thinking", "credits": 18, "nqf": 8},
                {"code": "INF4027W", "title": "System Development Project II", "credits": 40, "nqf": 8},
                {"code": "INF4024W", "title": "Information Systems Research Project", "credits": 60, "nqf": 8},
                {"code": "INF4025S", "title": "Information Systems Management", "credits": 20, "nqf": 8},
            ]},
        ]
    },
    {
        "programme_code": "CB004ECO01",
        "programme_name": "Bachelor of Business Science specialising in Economics",
        "degree": "BBusSci",
        "specialisation": "Economics",
        "nqf_level": 8,
        "minimum_credits": 528,
        "duration_years": 4,
        "slug": "bbusc-economics",
        "department": "economics",
        "years": [
            {"year": 1, "credits": 132, "courses": [
                {"code": "ACC1021F", "title": "Accounting for Business I", "credits": 15, "nqf": 5},
                {"code": "ACC1022Z", "title": "Accounting for Business II", "credits": 9, "nqf": 5},
                {"code": "ECO1010F", "title": "Microeconomics I", "credits": 18, "nqf": 5},
                {"code": "INF1002F", "title": "Foundations of Information Systems", "credits": 18, "nqf": 5},
                {"code": "MAM1010F", "title": "Mathematics 1010", "credits": 18, "nqf": 5},
                {"code": "ECO1011S", "title": "Macroeconomics I", "credits": 18, "nqf": 5},
                {"code": "MAM1012S", "title": "Mathematics 1012", "credits": 18, "nqf": 5},
                {"code": "STA1000S", "title": "Introductory Statistics", "credits": 18, "nqf": 5},
            ]},
            {"year": 2, "credits": 156, "courses": [
                {"code": "CML1001F", "title": "Business Law I", "credits": 18, "nqf": 5},
                {"code": "ECO2003F", "title": "Microeconomics II", "credits": 18, "nqf": 6},
                {"code": "FTX2020F", "title": "Business Finance", "credits": 18, "nqf": 6, "or": "FTX2024F"},
                {"code": "STA2020F", "title": "Applied Statistics", "credits": 24, "nqf": 6},
                {"code": "BUS2010F", "title": "Marketing I", "credits": 18, "nqf": 6},
                {"code": "ECO2004S", "title": "Macroeconomics II", "credits": 18, "nqf": 6},
                {"code": "ECO2007S", "title": "Co-operation and Competition", "credits": 18, "nqf": 6},
                {"code": "STA2030S", "title": "Theory of Statistics", "credits": 24, "nqf": 6, "or": "STA3022F"},
            ]},
            {"year": 3, "credits": 162, "courses": [
                {"code": "BUS2033F", "title": "Professional Communication", "credits": 18, "nqf": 7, "or": "BUS2033S"},
                {"code": "BUS3039F", "title": "People Management", "credits": 18, "nqf": 7, "or": "BUS3039S"},
                {"code": "ECO3020F", "title": "Advanced Macro & Microeconomics", "credits": 18, "nqf": 7},
                {"code": "FTX3044F", "title": "Investment Management A", "credits": 18, "nqf": 7},
                {"code": "STA3030F", "title": "Statistical Inference & Modelling", "credits": 36, "nqf": 7},
                {"code": "ECO3021S", "title": "Quantitative Methods in Economics", "credits": 18, "nqf": 7},
                {"code": "FTX3045S", "title": "Investment Management B", "credits": 18, "nqf": 7},
                {"code": "STA3036S", "title": "Operational Research Techniques", "credits": 36, "nqf": 7},
            ]},
            {"year": 4, "credits": 140, "note": "Core 78 credits + 2 electives from list", "courses": [
                {"code": "BUS4050H", "title": "Strategic Thinking", "credits": 18, "nqf": 8},
                {"code": "ECO4006F", "title": "Macroeconomics", "credits": 16, "nqf": 8},
                {"code": "ECO4007F", "title": "Microeconomics", "credits": 16, "nqf": 8},
                {"code": "ECO4016F", "title": "Econometrics", "credits": 16, "nqf": 8},
                {"code": "ECO4112F", "title": "Mathematics and Statistics for Economists", "credits": 16, "nqf": 8},
                {"code": "ECO4021W", "title": "Research and Writing I (Long Paper)", "credits": 30, "nqf": 8},
            ]},
        ]
    },
    {
        "programme_code": "CB004ECO03",
        "programme_name": "Bachelor of Business Science specialising in Economics with Law",
        "degree": "BBusSci",
        "specialisation": "Economics with Law",
        "nqf_level": 8,
        "minimum_credits": 528,
        "duration_years": 4,
        "slug": "bbusc-economics-law",
        "department": "economics",
    },
    {
        "programme_code": "CB004BUS07",
        "programme_name": "Bachelor of Business Science specialising in Marketing",
        "degree": "BBusSci",
        "specialisation": "Marketing",
        "nqf_level": 8,
        "minimum_credits": 528,
        "duration_years": 4,
        "slug": "bbusc-marketing",
        "department": "management-studies",
    },
    {
        "programme_code": "CB004BUS28",
        "programme_name": "Bachelor of Business Science specialising in Industrial and Organisational Psychology",
        "degree": "BBusSci",
        "specialisation": "Industrial and Organisational Psychology",
        "nqf_level": 8,
        "minimum_credits": 528,
        "duration_years": 4,
        "slug": "bbusc-io-psychology",
        "department": "management-studies",
    },

    # ============================================================
    # BACHELOR OF COMMERCE (BCom) - 3 year, NQF 7
    # ============================================================
    {
        "programme_code": "CB019BUS01",
        "programme_name": "Bachelor of Commerce in Actuarial Science",
        "degree": "BCom",
        "specialisation": "Actuarial Science",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-actuarial-science",
        "department": "management-studies",
    },
    {
        "programme_code": "CB019BUS09",
        "programme_name": "Bachelor of Commerce in Actuarial Science specialising in Quantitative Finance",
        "degree": "BCom",
        "specialisation": "Actuarial Science - Quantitative Finance",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-actuarial-quantitative-finance",
        "department": "management-studies",
    },
    {
        "programme_code": "CB001ACC08",
        "programme_name": "Bachelor of Commerce specialising in Financial Accounting: General Accounting",
        "degree": "BCom",
        "specialisation": "Financial Accounting - General Accounting",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-financial-accounting-general",
        "department": "accounting",
    },
    {
        "programme_code": "CB001ACC04",
        "programme_name": "Bachelor of Commerce specialising in Financial Accounting: Chartered Accountant",
        "degree": "BCom",
        "specialisation": "Financial Accounting - Chartered Accountant",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-financial-accounting-ca",
        "department": "accounting",
    },
    {
        "programme_code": "CB001INF01",
        "programme_name": "Bachelor of Commerce specialising in Information Systems",
        "degree": "BCom",
        "specialisation": "Information Systems",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-information-systems",
        "department": "information-systems",
    },
    {
        "programme_code": "CB001INF06",
        "programme_name": "Bachelor of Commerce specialising in Information Systems and Computer Science",
        "degree": "BCom",
        "specialisation": "Information Systems and Computer Science",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-is-computer-science",
        "department": "information-systems",
    },
    {
        "programme_code": "CB001INF11",
        "programme_name": "Bachelor of Commerce specialising in Information Systems and Finance",
        "degree": "BCom",
        "specialisation": "Information Systems and Finance",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-is-finance",
        "department": "information-systems",
    },
    {
        "programme_code": "CB001PHI03",
        "programme_name": "Bachelor of Commerce specialising in Philosophy, Politics and Economics (PPE)",
        "degree": "BCom",
        "specialisation": "Philosophy, Politics and Economics",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-ppe",
        "department": "economics",
    },
    {
        "programme_code": "CB001ECO02",
        "programme_name": "Bachelor of Commerce specialising in Economics and Finance",
        "degree": "BCom",
        "specialisation": "Economics and Finance",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-economics-finance",
        "department": "economics",
    },
    {
        "programme_code": "CB001ECO04",
        "programme_name": "Bachelor of Commerce specialising in Economics and Statistics",
        "degree": "BCom",
        "specialisation": "Economics and Statistics",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-economics-statistics",
        "department": "economics",
    },
    {
        "programme_code": "CB001ECO03",
        "programme_name": "Bachelor of Commerce specialising in Economics with Law",
        "degree": "BCom",
        "specialisation": "Economics with Law",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-economics-law",
        "department": "economics",
    },
    {
        "programme_code": "CB001BUS06",
        "programme_name": "Bachelor of Commerce specialising in Management Studies",
        "degree": "BCom",
        "specialisation": "Management Studies",
        "nqf_level": 7,
        "minimum_credits": 440,
        "duration_years": 3,
        "slug": "bcom-management-studies",
        "department": "management-studies",
        "note": "Flexible programme with electives. 416 total credits with 120 at NQF level 7."
    },
]

def build_programme_json(prog):
    """Convert programme dict to the handbook JSON format."""
    result = {
        "$schema": "handbook-programme-v1",
        "programme_code": prog["programme_code"],
        "programme_name": prog["programme_name"],
        "degree": prog["degree"],
        "specialisation": prog["specialisation"],
        "faculty": "commerce",
        "nqf_level": prog["nqf_level"],
        "minimum_credits": prog["minimum_credits"],
        "duration_years": prog["duration_years"],
        "department": prog["department"],
    }
    if "note" in prog:
        result["note"] = prog["note"]

    if "years" in prog:
        years_out = []
        for yr in prog["years"]:
            year_data = {
                "year": yr["year"],
                "total_credits": yr.get("credits", 0),
                "courses": []
            }
            if "note" in yr:
                year_data["note"] = yr["note"]
            for c in yr.get("courses", []):
                course = {
                    "code": c["code"],
                    "title": c["title"],
                    "nqf_credits": c["credits"],
                    "nqf_level": c["nqf"],
                }
                if "or" in c:
                    course["alternative"] = c["or"]
                year_data["courses"].append(course)
            years_out.append(year_data)
        result["curriculum"] = years_out

    return result


count = 0
for prog in programmes:
    data = build_programme_json(prog)
    filename = f"{prog['slug']}.json"
    filepath = os.path.join(OUTPUT_DIR, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    count += 1

print(f"Generated {count} programme files in {OUTPUT_DIR}")
